Yggdroot/LeaderF

autoload/leaderf/utils.py
When LC_ALL and LANG envs are both empty, the python code will raise an exception and get the following crash stack:
```python
Error detected while processing function leaderf#startFileExpl[2]..leaderf#LfPy:
line    2:
File "/Users/xxx/.vim/bundle/LeaderF/autoload/leaderf/manager.py", line 443, in startExplorer
self._content = self._getExplorer().getContent(*args, **kwargs)
File "/Users/xxx/.vim/bundle/LeaderF/autoload/leaderf/fileExpl.py", line 172, in getContent
self._content = self._getFileList(dir)
File "/Users/xxx/.vim/bundle/LeaderF/autoload/leaderf/fileExpl.py", line 21, in deco
cwd_length = len(lfEncoding(dir))
File "/Users/xxx/.vim/bundle/LeaderF/autoload/leaderf/utils.py", line 29, in lfEncoding
if …
```
=> [Bug fix]avoid crashing on Mac OSX

autoload/leaderf/instance.py, autoload/leaderf/manager.py
On neovim version 0.2.0-480-g25427ae89, I was unable to use the \<leader\>f shortcut.  The below fixed it for me.  I hope this can help others.
=> 'modifiable' attribute must have a Boolean value

autoload/leaderf/colorscheme/gruvbox.vim
This color scheme only works when gruvbox is the default color scheme.
see also: https://github.com/morhetz/gruvbox/blob/master/autoload/lightline/colorscheme/gruvbox.vim
=> add gruvbox colorscheme

autoload/leaderf/python/leaderf/mru.py
1. case insensitive mru file name manipulation on windows & cygwin & msys.
2. normalize path name before add to mru database.
=> Case insensitive mru file name manipulation on Windows

autoload/leaderf/python/leaderf/manager.py
To reproduce the problem:
* execute `:LeaderfFile`
* close the window with `Ctrl+C`
* execute `:%bw`
* execute `:LeaderfFile`
=> Fix hang when the instance buffer is wiped

autoload/leaderf/python/leaderf/manager.py, autoload/leaderf/python/leaderf/mru.py
我最近再用 LanguageClient，它给我搞跳转时，有时候文件名被弄成：
```text
\\?\D:\ACM\github\BasicBitmap\BasicBitmap.cpp
```
导致又出现重复文件：
```text
BasicBitmap.h              "D:\ACM\github\BasicBitmap\"
BasicBitmap.h              "E:\Lesson\lesson\encoder\"
BasicBitmap.cpp            "D:\ACM\github\BasicBitmap\"
BasicBitmap.cpp            "\\?\D:\ACM\github\BasicBitmap\"
BasicBitmap.cpp            "E:\Lesson\lesson\encoder\"
```
我测试了一下 python 的 os.path.isabs 测试哪个 `\\?\` 开头的路径，居然返回 True，我不知道 language server 怎么搞的居然会给我打开这种名字的文件，所以加了点处理代码。麻烦 review 以下。
=> Win32 下 MRU 文件名归一化优化，怎加一些边界情况判断

autoload/leaderf.vim, autoload/leaderf/python/leaderf/functionExpl.py, doc/leaderf.txt
添加一个 `g:Lf_CtagsFuncOpts` 选项，让用户可以自定义使用 `LeaderfFunction` 时的 `ctags` 选项
=> add ctags function expl options

autoload/leaderf/python/leaderf/fileExpl.py
One of the projects I work in regularly has a couple of submodules, and the default LeaderF implementation does not show the files in these submodules. This change fixes this with no negative impact on projects that do not have submodules.
=> Allow LeaderF to work with Git submodules

autoload/leaderf/colorscheme/one.vim
Hi, i added one-dark colorscheme for leaderF inspired by [lightline.vim](https://github.com/itchyny/lightline.vim) one-dark colorscheme
=> add one-dark colorscheme for leaderF

autoload/leaderf.vim, autoload/leaderf/python/leaderf/fileExpl.py, doc/leaderf.txt
支持用户设置工作目录，原因有两个：
1. 多个插件都各自搜索了一次工作目录，工作重复了，比如： https://github.com/jsfaint/gen_tags.vim/pull/77
2. 我想实现 farthestAncestor，又得另一个插件也要实现一遍，还不如在自己的 vimrc 里实现，然后传给插件。所以我把提交给 jsfaint/gen_tags.vim 的支持 farthestAncestor 合并请求关了，我会再去提交一个跟这个合并请求类似的。
比如：我把工程目录传给 vim-grepper 是这样的：
```
let g:grepper.ag.grepprg = 'ag --vimgrep $* '.g:root_dir
```
传给 LeaderF 是这样的：
```
let g:Lf_WorkingDirectory = g:root_dir
```
=> Add option g:Lf_WorkingDirectory to set working directory by user.

README.md, autoload/leaderf/Any.vim, autoload/leaderf/python/leaderf/rgExpl.py
通过 `--type-add` 可以设置自定义的文件类型
```viml
xnoremap gs :<C-U><C-R>=printf("Leaderf! rg -F --type-add 'decl:*.decl' -t decl -t c -t py -t lua --nowrap --stayOpen -e %s ", leaderf#Rg#visual())<cr><cr>
```
=> Add rg option --type-add

autoload/leaderf/python/leaderf/cli.py
see https://github.com/equalsraf/neovim-qt/issues/605 for details.
The current code created a state of (as pseudocode) 
```
while true 
getchar(1)
```
While I tested shorter sleep durations, none seemed to avoid the bug effectively enough. 
It is possible to apply this code only in Guis / only in neovim-qt. 
There is a slight reduction in performance of course, but not very prominent.
=> fix issue 375(LeaderF hangs in nvim-qt) 

autoload/leaderf/colorscheme/gruvbox_material.vim, autoload/leaderf/colorscheme/popup/gruvbox_material.vim
This PR will add [gruvbox-material](https://github.com/sainnhe/gruvbox-material) color scheme for both status line and popup window.
I'm using [this logic](https://github.com/sainnhe/gruvbox-material/blob/master/colors/gruvbox-material.vim#L482-L487) to enable leaderf color scheme in my repository, but it's really inefficient, so I think it might be better to add them in your repository.
=> add gruvbox-material color scheme

autoload/leaderf.vim, autoload/leaderf/python/leaderf/historyExpl.py, doc/leaderf.txt
I'd like to add an option that allows you to delete `:LeaderfHistory*` records using regular expressions.
I wanted to do the same because I deleted the line from the command line window as follows:
```vim
autocmd MyAutoCmd CmdwinEnter : silent g/\v^wq?!?/"_d
```
Thank you for your consideration.
Usage
```vim
let g:Lf_HistoryExclude = {
\   'cmd': ['^w!?', '^q!?', '^.\s*$'],
\   'search': ['^Plug']
\}
```
=> New option `g:Lf_HistoryExclude` to delete `:LeaderfHistory*` records

doc/leaderf.txt
"'top' and 'bottom'." should be "'top' or 'bottom'." as it obviously cannot be both simultaneously.
=> Fix gamattical mistake.

autoload/leaderf/python/leaderf/fileExpl.py, autoload/leaderf/python/leaderf/gtagsExpl.py, autoload/leaderf/python/leaderf/mruExpl.py
Use `get()` method to get values from dictionary options.
Because an error occurred when the following settings were made. (when there is no `'dir'` in the key)
```vim
let g:Lf_WildIgnore = {'file': ['*.py']}
```
Error:
```
行    1:
File "C:\Users\takuya\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 780, in start
the_args.start(arguments, *args, **kwargs)
File "C:\Users\takuya\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 712, in _default_action
manager.startExplorer(win_pos[2:], *args, **kwargs)
File "C:\Users\takuya\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 729, in startExplorer
super(FileExplManager, …
```
=> Use get() when get from dict options

autoload/leaderf.vim, autoload/leaderf/Cmd_History.vim, autoload/leaderf/History.vim, autoload/leaderf/Search_History.vim, autoload/leaderf/python/leaderf/historyExpl.py, autoload/leaderf/python/leaderf/manager.py, doc/leaderf.txt
Hi.
I implemented a command that can edit the command.
* Added help (`F1`) in normal mode.
* Added insert mode mappings.
* Added popup window (float window) mappings.
* Added new option `g:Lf_HistoryEditPromptIfEmpty`
Because the function of `leaderf#*#NormalModeFilter()` was called in `StlCategory`, the files were split into `Cmd_History.vim` and `Search_History.vim`. However, since the mapping is the same, we call `leaderf#History#NormalModeFilter()`.
Prompts for editing are not prepared on their own, but use the prompts of Vim. This is because input completion is effective and incremental search can be performed.
~What I couldn't do was start editing in insert mode. Does this have to give up?~
Could be implemented using `_cmdExtension()`.
Please give me a review when you have time. …
=> Added a command to edit history entry.

README.md, autoload/leaderf/Any.vim, autoload/leaderf/Command.vim, autoload/leaderf/python/leaderf/anyExpl.py, autoload/leaderf/python/leaderf/commandExpl.py, autoload/leaderf/python/leaderf/manager.py, autoload/leaderf/python/leaderf/selfExpl.py, doc/leaderf.txt
I tried to implement `command` which is one of #451.
When executing a command, if a command requires an argument (`E471`), it can now be automatically entered on the command line.
Also, the line can be edited with `e` (normal mode) or `C-o` (input mode) like cmdHistory/searchHistory.
Please let us know if any changes are missing.
Thank you.
=> Add command LeaderfCommand

autoload/leaderf/python/leaderf/historyExpl.py
Use `instance._cli._cmdline` instead of `instance._cli.pattern`.
```
function leaderf#Any#start[4]..leaderf#LfPy の処理中にエラーが検出されました:
行    1:
File "C:\Users\tamago324\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 788, in start
the_args.start(arguments, *args, **kwargs)
File "C:\Users\tamago324\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 720, in _default_action
manager.startExplorer(win_pos[2:], *args, **kwargs)
File "C:\Users\tamago324\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2015, in startExplorer
self.input()
File "C:\Users\tamago324\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 57, in deco …
```
=> Fix editHistory()

autoload/leaderf/Rg.vim, autoload/leaderf/python/leaderf/rgExpl.py, doc/leaderf.txt
You can output the result of filtering.
`Q` (quickfix list) and `L` (location list) can be output in `normal` mode.
Also added the `g:Lf_RgStorePattern` option to save the search pattern specified by `-e` in the register.
Refer #447.
=> Output quickfix

autoload/leaderf/Gtags.vim, doc/leaderf.txt, plugin/leaderf.vim
Add:
| Map                                        | Description
| ---                                        | -----------
| `<Plug>LeaderfGtagsDefinition`               | Show <cword> or selected text locations of definitions.
| `<Plug>LeaderfGtagsReference`                | Show <cword> or selected text reference to a symbol which has definitions.
| `<Plug>LeaderfGtagsSymbol`                   | Show <cword> or selected text reference to a symbol which has no definition.
| `<Plug>LeaderfGtagsGrep`                     | Show all lines which match to the <cword> or selected text .
=> Add Gtags commonly used mapping as <Plug>

autoload/leaderf/python/leaderf/manager.py
If the selected line is a help line, move the cursor like `accept()`.
=> Fix addSelection()

autoload/leaderf/python/leaderf/colorschemeExpl.py
`:colorscheme` can search `&packpath` and choose a candidate.
`:LeaderfColorscheme` also thinks it's better to search `&packpath` in the same way.
Thank you.
=> LeaderfColorscheme support packpath 

autoload/leaderf/fuzzyMatch_C/setup.py
gcc 4.8.5 failed to build the fuzzy match extension, messages list below
```bash
fuzzyEngine.c: In function ‘rg_getDigest’:
fuzzyEngine.c:1432:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
for ( char *p = s; p < s + len; ++p )
^
fuzzyEngine.c:1432:13: note: use option -std=c99 or -std=gnu99 to compile your code
fuzzyEngine.c:1460:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
for ( char *p = s; p < s + len; ++p )
^
```
=> fix building fuzzy match extension with old gcc

autoload/leaderf.vim, autoload/leaderf/python/leaderf/devicons.py, autoload/leaderf/python/leaderf/instance.py
When the colorscheme was loaded, `hi clear` was executed, removing the icon's highlights.
Is this the right way to go?
=> autocmd ColorScheme call highlightDevIcons()

autoload/leaderf/python/leaderf/bufExpl.py
Added `len('[No Name]')` to the minimum buffer name length.
=> Fix bufname min length

autoload/leaderf/python/leaderf/bufExpl.py, autoload/leaderf/python/leaderf/gtagsExpl.py, autoload/leaderf/python/leaderf/manager.py, autoload/leaderf/python/leaderf/mruExpl.py, autoload/leaderf/python/leaderf/rgExpl.py
Fixed an issue where a line less than the help length could not be deleted when the display was reversed.
=> Fix can't delete if less than help length

autoload/leaderf/python/leaderf/anyExpl.py
When I formatted the list with format_list, I got the following error:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
File "C:\Users\user\ghq\github.com\tamago324\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 797, in start
the_args.start(arguments, *args, **kwargs)
File "C:\Users\user\ghq\github.com\tamago324\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 729, in _default_action
manager.startExplorer(win_pos[2:], *args, **kwargs)
File "C:\Users\user\ghq\github.com\tamago324\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 367, in startExplorer
super(AnyExplManager, …
```
=> Fix format_list error

autoload/leaderf/python/leaderf/manager.py, doc/leaderf.txt
Added `"_"` to `g:Lf_NormalMap`.
Refer #503.
`"_"` is a mapping that applies to all categories.
Also, the mapping of each category overrides the mapping of `"_"`.
For example, to change the mapping for the File category only, do the following.
```vim
let g:Lf_NormalMap = {
\   "_": [
\      ['<C-j>', 'j'],
\      ['<C-k>', 'k'],
\   ],
\   "File": [
\      ['<C-j>', '<Nop>'],
\      ['<C-k>', '<Nop>'],
\   ],
\}
```
Thank you!
=> Common normal map

autoload/leaderf/python/leaderf/manager.py
The preview was not working correctly in Vim when viewed with popup.
```
:Leaderf file --popup
```
The settings are as follows.
```
let g:Lf_PreviewInPopup = 0
```
Refer https://github.com/tamago324/LeaderF-filer/issues/31.
Thank you.
=> Fix preview command [Vim]

autoload/leaderf/python/leaderf/manager.py
The title of the popup preview will now show an icon.
Refer https://github.com/tamago324/LeaderF-filer/issues/31#issuecomment-616007459
Before:
After:
Thank you!
=> Fix preview poup title

autoload/leaderf/python/leaderf/anyExpl.py
Some Japanese Kanji characters were garbled, so that has been fixed.
I'm sorry, but I haven't been able to confirm that it doesn't affect other languages.
<details>
<summary>minvimrc</summary>
```vim
set encoding=utf-8
scriptencoding utf-8
syntax enable
filetype plugin indent on
set nocompatible
set runtimepath^=~/ghq/github.com/tamago324/LeaderF
" no backup
set nobackup
set nowritebackup
" no swap
set noswapfile
set updatecount=0
" 消せる文字
set backspace=indent,eol,start
nnoremap <silent> <Space>q :<C-u>quit<CR>
nnoremap <silent> <Space>Q :<C-u>quit!<CR>
" ====================
" help
" ====================
let s:fav_helps = [
\   ['function-list',      '関数一覧'],
\   ['user-commands',      'command の書き方'],
\   ['autocmd-events',     'autocmd 一覧'],
\   ['E500',               '<cword> とか …
```
=> Fix garbled in VimScript extensions [Win10]

autoload/leaderf/colorscheme/gruvbox_material.vim, autoload/leaderf/colorscheme/one.vim
Using `default` was preventing these colorschemes from being used.
=> Fix one and gruvbox_material palette names

autoload/leaderf/python/leaderf/cli.py
This PR solves the problem shown in the gif below.
In the gif above, I use `V` to select the line. Then type `<C-v>` to paste the content. The char `\n` at the end of the line leads to blink problem.
Also I propose that we should avoid multiple lines as input. Therefore I made a line break at the first `\n`.
=> fix leaderf blink if input contains `\n`

autoload/leaderf/python/leaderf/gtagsExpl.py
update vim vars before gtags update.
then I can modify some vim var like `g:Lf_WildIgnore`, and update gtags without reopen vim.
=> update vim vars before gtags update

autoload/leaderf/python/leaderf/rgExpl.py
The output was not correct when `g:Lf_Config` contains `--column`.
This has been corrected.
Thank you!
=> Fix outputToQfList when it has a column

autoload/leaderf/python/leaderf/gtagsExpl.py, autoload/leaderf/python/leaderf/mruExpl.py, autoload/leaderf/python/leaderf/qfloclistExpl.py, autoload/leaderf/python/leaderf/rgExpl.py, autoload/leaderf/python/leaderf/tagExpl.py
This PR solves the following issue:
- Start nvim/vim and there will be a `[No Name]` buffer stays here
- `:Leaderf rg`
- Press `<CR>` to open an arbitrary file
Then the file will be opened in a new buffer, while that `[No Name]` buffer still exists.
Normally the `[No Name]` buffer should be replaced by that file.
This also occurs when I use `mru`, `gtags`, etc. But `:Leaderf file` works normally. So I made some changes corresponding to  `fileExpl.py`.
- before
- after
=> only use `drop` to open selected if the buffer already exists

autoload/leaderf/python/leaderf/utils.py
I am using a frontend framework that use `/somepage/$id/index.tsx` to do routing. But LeaderF cannot open file with `$`  in the path name.
=> escSpecial escapes dollar mark

autoload/leaderf/Rg.vim
The bug was caused because the pattern was not enclosed in braces. bug #646
=> Resolves bug #646

autoload/leaderf/python/leaderf/instance.py, autoload/leaderf/python/leaderf/manager.py, doc/leaderf.txt
* Add a option g:Lf_DisableStl, which will stop LeaderF rendering stasusline
* Add a buffer-scoped variable "b:Lf_category" in LeaderF buffer,
which stores the category of current LeaderF session, then we
can use like `eval(printf("g:Lf_%s_StlMode", b:Lf_category))`
or `eval("get(g:, 'Lf_" . b:Lf_category . "_StlResultsCount', -1)")`
to get status of LeaderF
* Only test on the plugin lightline
* Some lightline setting example
```vimL
let g:lightline.active = {
\ 'left': [ ['mode_', 'paste'], ['filename_', 'filestatus_'] ],
\ 'right': [ ['percent', 'lineinfo_']
\}
let g:lightline.component_function = {
\   'mode_': 'LightlineMode',
\   'filename_': 'LightlineFilename',
\   'filestatus_': 'LightlineFilestatus',
\   'lineinfo_': 'LightlineLineinfo'
\}
function! LightlineMode()
let fname = …
```
=> More compatible with other statusline plugin.

doc/leaderf.txt
=> Fix help tag duplicate and trailing whitespace

autoload/leaderf/python/leaderf/instance.py
leaderf buffer, which has been set to `nobuflisted`, became `buflisted` after reopening. We should `_setAttributes` one more time.
=> fix leaderf buffer becomes buflisted when invoked again

autoload/leaderf/python/leaderf/fileExpl.py
after set g:Lf_JumpToExistingWindow to 0.
如果 `g:Lf_JumpToExistingWindow` 为 0 上图选择Drop就变成Edit了。
=> Fix :Leaderf file drop option for <C-\> shortcuts not work

autoload/leaderf/python/leaderf/gtagsExpl.py
Hi! When I try to preview a `Leaderf gtags` result in an exist buffer I get this error
```
Error invoking 'python_execute' on channel 4 (python3-script-host):
File "/Users/xutianshu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 386, in _previewResult
self._previewInPopup(line, self._getInstance().buffer, line_nr)
File "/Users/xutianshu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 1225, in _previewInPopup
self._createPopupPreview("", source, line_num)
File "/Users/xutianshu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 91, in deco
func(self, *args, **kwargs)
File "/Users/xutianshu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py …
```
=> Fix: gtags preview bug

autoload/leaderf/python/leaderf/manager.py
This logic error sometimes causes fatal
```
Error invoking 'python_execute' on channel 8 (python2-script-host):
File "/Users/xutianshu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
the_args.start(arguments, *args, **kwargs)
File "/Users/xutianshu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
manager.startExplorer(win_pos[2:], *args, **kwargs)
File "/Users/xutianshu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 884, in startExplorer
super(RgExplManager, self).startExplorer(win_pos, *args, **kwargs)
File "/Users/xutianshu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2298, in …
```
=> fix fuzzymatch

plugin/leaderf.vim
Summary: fix "reverse range in character class" error when triggering autocommand for a buffer with a name containing reverse regex character class (range of chars in square braces like `[a-z]`, but with the right side < left side: `[z-a]`) as a part of a name.
In particular triggers for luadev buffer which has a default name `[nvim-lua]`
=> fix "reverse range in character class" error

autoload/leaderf/python/leaderf/manager.py
fixed `vim.error: Vim:E118: 函数的参数过多: getcwd` in vim 7.4.629
It is caused by `getcwd(winnr())` in `line 1912` in `manager.py`
I have tested this PR in vim 8.1 and nvim0.5+， no bugs found
=> fixed vim.error: Vim:E118: 函数的参数过多: getcwd in vim 7.4.629

autoload/leaderf/python/leaderf/instance.py
If set g:Lf_PopupPosition to [1, 0], then the search window will not
show from the first line in neovim. Fix it.
Signed-off-by: Adam Tao <tcx4c70@gmail.com>
=> Fix g:Lf_PopupPosition in neovim

autoload/leaderf/python/leaderf/gtagsExpl.py
warning and error both output to stderr. So error is not null. The issue happens.
Now use the return code to avoid take warning as error.
=> fixe issue #928

autoload/leaderf/python/leaderf/rgExpl.py
Introduce "ensure_ascii=False" parameter for json.dumps in rgExpl.py to fix #948 when writing non ASCII characters to quickfix.
=> Fix issue #948

autoload/leaderf/python/leaderf/manager.py, doc/leaderf.txt
Maybe it's not an elegant solution, but it's useful to scroll more in the preview window.
=> Add g:Lf_PreviewScrollStepSize to scroll more in the preview window.

install.bat
same as the `install.sh` way
when build with python 3.11, the `.pyd` file is in `lib.win-amd64-cpython-311`. can not pushd use `pushd build\lib*3.*`
=> install.bat use --build-lib instead of copy file

autoload/leaderf/python/leaderf/mru.py, autoload/leaderf/python/leaderf/mruExpl.py
在 vim9 、python10 及 windows10 中文版的環境中，mruExpl 及 mru 在將中文檔名寫入 mruCache 會出現encoding錯誤，而無法記錄最近開啟的中文檔，爰修正將檔名指定以utf8編碼寫入mruCache。
=> 修正中文檔名無法寫入mruCache問題

autoload/leaderf/python/leaderf/bufExpl.py, autoload/leaderf/python/leaderf/rgExpl.py
When using
```
:Leaderf buffer --nameOnly --auto-preview
```
if the input does not match any buffer, string variable `line` is empty and the method `_previewInPopup` will raise a ValueError.
=> fix bugs in bufExpl.py and rgExpl.py

autoload/leaderf.vim, autoload/leaderf/python/leaderf/commandExpl.py, autoload/leaderf/python/leaderf/jumpsExpl.py
in vim7.4, no function `execute()` exists, so `leader jumps`, `leaderf command` would raise errors,  this commit fixed this bug
=> add leader#execute func if execute() function not exists

autoload/leaderf/python/leaderf/manager.py
The first commit is simply modify the 'argdelete' cmd;
The second commit fix the issue in multi seletion with path argument provided like `leader file /path/to/files`.
In multi selection those files need to be prefixed with cwd.
=> simplify argdelete and prefix path to multi file selection

autoload/leaderf/Command.vim
LeaderF command  命令无法从 normal mode 切换回 insert mode
=> fix: variable g:Lf_pI not defined when switch normal mode to insert mode in LeaderfCommand

autoload/leaderf/fuzzyMatch_C/setup.py, install.bat
In msys/mingw/ucrt python enviroment, the `install.bat` will not find `py.exe` and python was build using gccc not msvc. So `:LeaderfInstallCExtension` will fail.
=> support MSYS python enviroment

autoload/leaderf/python/leaderf/gtagsExpl.py
For large-scale projects like the Linux kernel source code, specifying gtags.files will significantly accelerate both the generation speed of GTAGS database and search operations.
=> Enable project-specific configuration of gtags.files
