Yggdroot/LeaderF

autoload/leaderf/mruExpl.py

when len(lines) == 0, you will get a crash.

fix a crash when I use MRUCwd

---

autoload/leaderf/python/leaderf/instance.py

add window position aboveleft and belowright

add window position aboveleft and belowright

---

install.sh

Support for various environments:
* Python2 isn't installed
* Python3 isn't installed
* Both Python versions aren't installed
* Both Python versions are installed

Add if python is present in system

---

autoload/leaderf/python/leaderf/historyExpl.py

fix issue #283

---

autoload/leaderf/python/leaderf/gtagsExpl.py
doc/leaderf.txt

Also fix a minor grammar issue

fix Lf_Gtagslabel variable name; update doc

---

doc/leaderf.txt

Fix #439 typo

---

README.md
autoload/leaderf/Any.vim
autoload/leaderf/Filetype.vim
autoload/leaderf/python/leaderf/anyExpl.py
autoload/leaderf/python/leaderf/filetypeExpl.py
autoload/leaderf/python/leaderf/manager.py
autoload/leaderf/python/leaderf/selfExpl.py
doc/leaderf.txt
plugin/leaderf.vim

I tried to implement `filetype` which is one of #451.
Please let us know if any changes are missing.
Thank you.

Add comamnd LeaderfFiletype

---

autoload/leaderf/python/leaderf/commandExpl.py

Sorry. There was a shortage at #455.
Fixed small bug.

Use histadd() after command executed

---

plugin/leaderf.vim

Notice that https://github.com/Yggdroot/LeaderF/pull/455#issuecomment-570155011 does not define `LeaderfCommand`.
sorry.

Add LeaderfCommand

---

autoload/leaderf/Any.vim
autoload/leaderf/python/leaderf/commandExpl.py
autoload/leaderf/python/leaderf/historyExpl.py

Could you tell me if anything is wrong with the option name or help text?

Add --run-immediately options

---

autoload/leaderf/python/leaderf/instance.py
doc/leaderf.txt

Added an option to resize automatically.
I was wondering whether to add an argument like `--auto-resize`. Is it necessary?

Add options "g:Lf_AutoResize"

---

README.md
autoload/leaderf/Any.vim
autoload/leaderf/Window.vim
autoload/leaderf/python/leaderf/anyExpl.py
autoload/leaderf/python/leaderf/manager.py
autoload/leaderf/python/leaderf/selfExpl.py
autoload/leaderf/python/leaderf/windowExpl.py
doc/leaderf.txt
plugin/leaderf.vim
syntax/leaderf.vim

I implemented a `:LeaderfWindow` command that can display a list of buffers displayed in windows on all tab pages.
Refer #471

Add command LeaderfWindow

---

autoload/leaderf/python/leaderf/windowExpl.py

Fix :Leaderf window matchadd highlight

---

autoload/leaderf/python/leaderf/devicons.py
doc/leaderf.txt

The following two icons can be added
* `g:Lf_DevIconsExactSymbols`
* `g:Lf_DevIconsExtensionSymbols`
The ability to add icons will allow for greater scalability.
Thank you.

Customizable devicons

---

autoload/leaderf/python/leaderf/cli.py

I want to show the current directory at the prompt in [LeaderF-filer](https://github.com/tamago324/LeaderF-filer/commit/fffd51a8e9289021b30cdb7ae9ad99488d036292).
To display it, the LeaderF side needs a property to display it in prompt.
Thank you!
I want to display the following:

custom cli prompt

---

autoload/leaderf.vim
autoload/leaderf/python/leaderf/devicons.py

There was a typo in the code I wrote. I'm sorry.

Fix typo (Pallete => Palette)

---

autoload/leaderf/Rg.vim

Added a function to return `-t` of `rg` from a file name.
Refer #526
Usage:
1. For example, let's map the following
```vim
nnoremap <Space>fg :<C-u><C-r>=printf('Leaderf rg %s ', leaderf#Rg#getTypeByFileName(expand('%')))<CR>
```
2. Type `<Space>fg`.
3. If the current buffer name is `sample.vim`, it will be `:Leaderf rg -t "vimscript" `
Thank you!

Add leaderf#Rg#getTypeByFileName()

---

autoload/leaderf/Window.vim
autoload/leaderf/python/leaderf/windowExpl.py

The `LeaderfWindow` delete command is implemented.
Thank you.

Add delete command of :LeaderfWindow

---

autoload/leaderf/python/leaderf/gtagsExpl.py
doc/leaderf.txt

add g:Lf_GtagsStoreInRootMarker

---

autoload/leaderf/python/leaderf/rgExpl.py

Fix issue #621

---

README.md
autoload/leaderf/Any.vim
autoload/leaderf/QfLocList.vim
autoload/leaderf/python/leaderf/anyExpl.py
autoload/leaderf/python/leaderf/manager.py
autoload/leaderf/python/leaderf/qfloclistExpl.py
autoload/leaderf/python/leaderf/selfExpl.py
doc/leaderf.txt
plugin/leaderf.vim
syntax/leaderf.vim

The following two commands have been added
* LeaderfQuickFix
* LeaderfLocList
Refer #558 
Thank you!

Add LeaderfQuickFix and LeaderfLocList

---

autoload/leaderf/python/leaderf/gtagsExpl.py
autoload/leaderf/python/leaderf/tagExpl.py

Actually, this is the real solution for #643.
Signed-off-by: Hao Lee <haolee.swjtu@gmail.com>

LeaderfTag should also take consider of Lf_JumpToExistingWindow

---

autoload/leaderf/python/leaderf/colorschemeExpl.py

Colorscheme non-systemed list above systemed.

---

autoload/leaderf/python/leaderf/gtagsExpl.py
doc/leaderf.txt

compatible with https://github.com/ludovicchabant/vim-gutentags

I use vim-gutentags to generate gtags, so i need compatibility

---

autoload/leaderf/python/leaderf/gtagsExpl.py

Sorry, I only test on windows in last PR.
When i test on linux, find a bug.

compatible with gutentags: fix bug on linux, I only test on windows in last commit

---

autoload/leaderf/Line.vim
autoload/leaderf/python/leaderf/lineExpl.py

I tried to make it so that it can be output to quickfix and loclist in the `Leaderf line` as in #488.
If you think it's good, I'd be happy to merge them.
Thank you!

Add command quickfix/loclist output ot `Leaderf line`

---

autoload/leaderf/python/leaderf/manager.py

This is a reopening of https://github.com/Yggdroot/LeaderF/pull/914

fix issue #913

---

autoload/leaderf/python/leaderf/manager.py

Fix issure #924

---

autoload/leaderf/python/leaderf/fileExpl.py
doc/leaderf.txt

查找檔案功能新增根據副檔名自訂處理命令 #947

---

autoload/leaderf/colorscheme/popup/solarized.vim
autoload/leaderf/colorscheme/solarized.vim

Extracted from https://github.com/phongnh/leaderf-settings.vim.
Thanks @phongnh

Add solarized colorscheme.

---

autoload/leaderf/colorscheme/onedark.vim
autoload/leaderf/colorscheme/popup/onedark.vim

add onedark colorscheme. suitable for [joshdick/onedark.vim](https://github.com/joshdick/onedark.vim)

add onedark colorscheme

---

README.md

See https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

Update font name for Droid Sans Mono Nerd Font Mono

---

autoload/lfMru.vim

check list length, before index it

check list length
